class Classifiers(object):
    id3 = 'weka.classifiers.trees.Id3'
    j48 = 'weka.classifiers.trees.J48'
    perceptron = 'weka.classifiers.functions.MultilayerPerceptron'
    naive_bayes = 'weka.classifiers.bayes.NaiveBayes'
    naive_bayes_simple = 'weka.classifiers.bayes.NaiveBayesSimple'
    logistic = 'weka.classifiers.functions.Logistic'
    zero = 'weka.classifiers.rules.ZeroR'
    ib1 = 'weka.classifiers.lazy.IB1'
    ibk = 'weka.classifiers.lazy.IBk'
    boost_stump = 'weka.classifiers.meta.AdaBoostM1'
    boost_id3 = 'weka.classifiers.meta.AdaBoostM1 -W weka.classifiers.trees.J48'
    boost_j48 = 'weka.classifiers.meta.AdaBoostM1 -W weka.classifiers.trees.J48'
    svm = 'weka.classifiers.functions.SMO'
